# LAB1: NumPy Exercises 


#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
a = np.zeros(10)

#### Create an array of 10 ones

In [4]:
b = np.ones(10)

#### Create an array of 10 fives

In [5]:
c = np.full(10, 5)

print(c)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [6]:
d = np.arange(10, 51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [7]:
e = np.arange(10, 51, 2)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
f = np.arange(0, 9).reshape(3, 3)

print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
g = np.random.rand(1)
print(g)

[0.27973651]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
h = np.random.randn(25)
print(h)

[ 0.80145186  1.97824621 -0.53263331  1.49052931 -0.45978266  0.4473574
  1.98502639 -0.54468627  1.1520346   0.49921335 -0.1941279  -2.38881343
  0.42931984  0.27999402  0.08612639  0.02802519 -0.90987797 -1.12870136
 -0.41320385 -0.28769038 -0.52788706 -1.10646295  0.93992806  0.88359874
  1.18248207]


#### Create the following matrix:

In [ ]:
i = np.linspace(0.01, 1, 100).reshape(10, 10)

print(i)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
j = np.linspace(0, 1, 20)

print(j)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Write a code that creates the following output**

```
[[12, 13, 14, 15],
[17, 18, 19, 20],
[22, 23, 24, 25]]
```

In [6]:
# Extract the desired sub-matrix
output = mat[2:, 1:]
print(output)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


20

In [12]:
output = mat[3, 4]
print(output)

20


```
array([[ 2],
       [ 7],
       [12]])
```

In [16]:
# take the 2nd column of the first 3 rows then reshape into a 3x1 column vector
output = mat[0:3, 1].reshape(-1, 1)
print(output)

[[ 2]
 [ 7]
 [12]]


```
array([21, 22, 23, 24, 25])
```

In [24]:
output = mat[4, :].reshape(1, 5)
print(output)

[[21 22 23 24 25]]


```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [31]:
output = mat[3:, :].reshape(2, 5)
print(output)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [7]:
total_sum = mat.sum()
print(total_sum)

325


#### Get the sum of all the columns in mat

In [8]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

#### Broadcasting

Given a=np.arange(3).reshape(3, 1) and b=np.arange(3):

- Predict the result of a + b without running the code.

- Explain the broadcasting rules at play.

- Create the arrays and run the results

- Implement a solution that would not rely on broadcasting (using np.tile or similar).

In [32]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3)

# To be completely honest, I do not know how to do this and I am short on time.
# I will just leave it as is and move on.

# Great Job!